language: php

notifications:
  slack:
    secure: HuIz/xcPEACJvah+/h5jX4JX8Z22wgK0ZBIwn/v1KDnbl3m62EdJAfGN3jvGD+n9njmYUOCjslLHAooAC1MNntUcB9D2PJAArjD3mb9e34VtSwZ7NMfHkHZSksuaWg+nEDJrFSChvxHBp03/4JoVWjJMM2cm1TdpOMR0a/eFY1s=

branches:
  except:
    - gh-pages

php:
  - 5.5
  - 5.6
  - hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - vendor/bin/phpunit --verbose

after_script:
  - php vendor/bin/coveralls -v
  - sh code-climate-coverage.sh
