var tree = [["Github","Github.html","",
                [["Api","Github\/Api.html","",
                [["CurrentUser","Github\/Api\/CurrentUser.html","",
                [["DeployKeys","Github\/Api\/CurrentUser\/DeployKeys.html"," < AbstractApi",
                [        ]],["Emails","Github\/Api\/CurrentUser\/Emails.html"," < AbstractApi",
                [        ]],["Followers","Github\/Api\/CurrentUser\/Followers.html"," < AbstractApi",
                [        ]],["Notifications","Github\/Api\/CurrentUser\/Notifications.html"," < AbstractApi",
                [        ]],["Starring","Github\/Api\/CurrentUser\/Starring.html"," < AbstractApi",
                [        ]],["Watchers","Github\/Api\/CurrentUser\/Watchers.html"," < AbstractApi",
                [        ]]        ]],["Enterprise","Github\/Api\/Enterprise.html","",
                [["License","Github\/Api\/Enterprise\/License.html"," < AbstractApi",
                [        ]],["Stats","Github\/Api\/Enterprise\/Stats.html"," < AbstractApi",
                [        ]]        ]],["GitData","Github\/Api\/GitData.html","",
                [["Blobs","Github\/Api\/GitData\/Blobs.html"," < AbstractApi",
                [        ]],["Commits","Github\/Api\/GitData\/Commits.html"," < AbstractApi",
                [        ]],["References","Github\/Api\/GitData\/References.html"," < AbstractApi",
                [        ]],["Tags","Github\/Api\/GitData\/Tags.html"," < AbstractApi",
                [        ]],["Trees","Github\/Api\/GitData\/Trees.html"," < AbstractApi",
                [        ]]        ]],["Issue","Github\/Api\/Issue.html","",
                [["Comments","Github\/Api\/Issue\/Comments.html"," < AbstractApi",
                [        ]],["Events","Github\/Api\/Issue\/Events.html"," < AbstractApi",
                [        ]],["Labels","Github\/Api\/Issue\/Labels.html"," < AbstractApi",
                [        ]],["Milestones","Github\/Api\/Issue\/Milestones.html"," < AbstractApi",
                [        ]]        ]],["Organization","Github\/Api\/Organization.html","",
                [["Members","Github\/Api\/Organization\/Members.html"," < AbstractApi",
                [        ]],["Teams","Github\/Api\/Organization\/Teams.html"," < AbstractApi",
                [        ]]        ]],["PullRequest","Github\/Api\/PullRequest.html","",
                [["Comments","Github\/Api\/PullRequest\/Comments.html"," < AbstractApi",
                [        ]]        ]],["Repository","Github\/Api\/Repository.html","",
                [["Assets","Github\/Api\/Repository\/Assets.html"," < AbstractApi",
                [        ]],["Collaborators","Github\/Api\/Repository\/Collaborators.html"," < AbstractApi",
                [        ]],["Comments","Github\/Api\/Repository\/Comments.html"," < AbstractApi",
                [        ]],["Commits","Github\/Api\/Repository\/Commits.html"," < AbstractApi",
                [        ]],["Contents","Github\/Api\/Repository\/Contents.html"," < AbstractApi",
                [        ]],["DeployKeys","Github\/Api\/Repository\/DeployKeys.html"," < AbstractApi",
                [        ]],["Downloads","Github\/Api\/Repository\/Downloads.html"," < AbstractApi",
                [        ]],["Forks","Github\/Api\/Repository\/Forks.html"," < AbstractApi",
                [        ]],["Hooks","Github\/Api\/Repository\/Hooks.html"," < AbstractApi",
                [        ]],["Labels","Github\/Api\/Repository\/Labels.html"," < AbstractApi",
                [        ]],["Releases","Github\/Api\/Repository\/Releases.html"," < AbstractApi",
                [        ]],["Statuses","Github\/Api\/Repository\/Statuses.html"," < AbstractApi",
                [        ]]        ]],["AbstractApi","Github\/Api\/AbstractApi.html","",
                [        ]],["ApiInterface","Github\/Api\/ApiInterface.html","",
                [        ]],["Authorizations","Github\/Api\/Authorizations.html"," < AbstractApi",
                [        ]],["CurrentUser","Github\/Api\/CurrentUser.html"," < AbstractApi",
                [        ]],["Enterprise","Github\/Api\/Enterprise.html"," < AbstractApi",
                [        ]],["Gists","Github\/Api\/Gists.html"," < AbstractApi",
                [        ]],["GitData","Github\/Api\/GitData.html"," < AbstractApi",
                [        ]],["Issue","Github\/Api\/Issue.html"," < AbstractApi",
                [        ]],["Markdown","Github\/Api\/Markdown.html"," < AbstractApi",
                [        ]],["Meta","Github\/Api\/Meta.html"," < AbstractApi",
                [        ]],["Organization","Github\/Api\/Organization.html"," < AbstractApi",
                [        ]],["PullRequest","Github\/Api\/PullRequest.html"," < AbstractApi",
                [        ]],["Repo","Github\/Api\/Repo.html"," < AbstractApi",
                [        ]],["User","Github\/Api\/User.html"," < AbstractApi",
                [        ]]        ]],["Exception","Github\/Exception.html","",
                [["ApiLimitExceedException","Github\/Exception\/ApiLimitExceedException.html"," < RuntimeException",
                [        ]],["BadMethodCallException","Github\/Exception\/BadMethodCallException.html"," < BadMethodCallException",
                [        ]],["ErrorException","Github\/Exception\/ErrorException.html"," < ErrorException",
                [        ]],["ExceptionInterface","Github\/Exception\/ExceptionInterface.html","",
                [        ]],["InvalidArgumentException","Github\/Exception\/InvalidArgumentException.html"," < InvalidArgumentException",
                [        ]],["MissingArgumentException","Github\/Exception\/MissingArgumentException.html"," < ErrorException",
                [        ]],["RuntimeException","Github\/Exception\/RuntimeException.html"," < RuntimeException",
                [        ]],["TwoFactorAuthenticationRequiredException","Github\/Exception\/TwoFactorAuthenticationRequiredException.html"," < RuntimeException",
                [        ]],["ValidationFailedException","Github\/Exception\/ValidationFailedException.html"," < ErrorException",
                [        ]]        ]],["HttpClient","Github\/HttpClient.html","",
                [["Cache","Github\/HttpClient\/Cache.html","",
                [["CacheInterface","Github\/HttpClient\/Cache\/CacheInterface.html","",
                [        ]],["FilesystemCache","Github\/HttpClient\/Cache\/FilesystemCache.html","",
                [        ]],["GaufretteCache","Github\/HttpClient\/Cache\/GaufretteCache.html","",
                [        ]]        ]],["Listener","Github\/HttpClient\/Listener.html","",
                [["AuthListener","Github\/HttpClient\/Listener\/AuthListener.html","",
                [        ]],["ErrorListener","Github\/HttpClient\/Listener\/ErrorListener.html","",
                [        ]]        ]],["Message","Github\/HttpClient\/Message.html","",
                [["ResponseMediator","Github\/HttpClient\/Message\/ResponseMediator.html","",
                [        ]]        ]],["CachedHttpClient","Github\/HttpClient\/CachedHttpClient.html"," < HttpClient",
                [        ]],["HttpClient","Github\/HttpClient\/HttpClient.html","",
                [        ]],["HttpClientInterface","Github\/HttpClient\/HttpClientInterface.html","",
                [        ]]        ]],["Client","Github\/Client.html","",
                [        ]],["ResultPager","Github\/ResultPager.html","",
                [        ]],["ResultPagerInterface","Github\/ResultPagerInterface.html","",
                [        ]]        ]]        ]

